//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digibox.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbdigiboxEntities : DbContext
    {
        public dbdigiboxEntities()
            : base("name=dbdigiboxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tmdistributor> tmdistributors { get; set; }
        public virtual DbSet<tmattribute> tmattributes { get; set; }
        public virtual DbSet<tmmaterialsbu> tmmaterialsbus { get; set; }
        public virtual DbSet<tmmaterial> tmmaterials { get; set; }
        public virtual DbSet<tmrole> tmroles { get; set; }
        public virtual DbSet<tmuser> tmusers { get; set; }
        public virtual DbSet<tmmaterialuser> tmmaterialusers { get; set; }
        public virtual DbSet<ttmessage> ttmessages { get; set; }
        public virtual DbSet<tmmaterialprice> tmmaterialprices { get; set; }
        public virtual DbSet<ttattachment> ttattachments { get; set; }
        public virtual DbSet<tdprice> tdprices { get; set; }
        public virtual DbSet<ttprice> ttprices { get; set; }
        public virtual DbSet<tduser> tdusers { get; set; }
        public virtual DbSet<tdrole> tdroles { get; set; }
        public virtual DbSet<tsfunction> tsfunctions { get; set; }
        public virtual DbSet<ttreplenish> ttreplenishes { get; set; }
        public virtual DbSet<tdreplenish> tdreplenishes { get; set; }
        public virtual DbSet<tdrequest> tdrequests { get; set; }
        public virtual DbSet<ttrequest> ttrequests { get; set; }
        public virtual DbSet<ttinventory> ttinventories { get; set; }
        public virtual DbSet<tdoutgoing> tdoutgoings { get; set; }
        public virtual DbSet<tddraw> tddraws { get; set; }
        public virtual DbSet<ttdraw> ttdraws { get; set; }
        public virtual DbSet<ttopnam> ttopnams { get; set; }
        public virtual DbSet<tdopnam> tdopnams { get; set; }
    }
}
