//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digibox.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmmaterial
    {
        public System.Guid id { get; set; }
        public string partno { get; set; }
        public string name { get; set; }
        public Nullable<decimal> minstock { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public Nullable<System.DateTime> deletedat { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public string deletedby { get; set; }
        public Nullable<decimal> currentstock { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public string description { get; set; }
        public Nullable<System.Guid> location { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<decimal> maxstock { get; set; }
        public System.Guid movementtype { get; set; }
        public System.Guid materialtype { get; set; }
        public System.Guid distributor { get; set; }
        public System.Guid binlocation { get; set; }
        public string plant { get; set; }
        public string sloc { get; set; }
        public string calhorizon { get; set; }
    }
}
