//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digibox.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmrole
    {
        public string name { get; set; }
        public string slug { get; set; }
        public string description { get; set; }
        public System.DateTime createdat { get; set; }
        public System.DateTime updateat { get; set; }
        public Nullable<System.DateTime> deletedat { get; set; }
        public Nullable<int> Special { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> updatedby { get; set; }
        public string deletedby { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public System.Guid id { get; set; }
    }
}
