//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digibox.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmuser
    {
        public string name { get; set; }
        public string email { get; set; }
        public string position { get; set; }
        public string password { get; set; }
        public Nullable<bool> isldap { get; set; }
        public string token { get; set; }
        public Nullable<long> costcenterid { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public Nullable<System.DateTime> deletedat { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public string deletedby { get; set; }
        public string status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public System.Guid id { get; set; }
        public Nullable<System.Guid> roleid { get; set; }
        public Nullable<bool> isdeletable { get; set; }
    }
}
